name: CI Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-on-pr:
    if: github.event_name == 'pull_request'
    name: Test on Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[test]'
      - name: Run tests
        run: pytest tests/ -v --cov=content_aggregator --cov-report=xml
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml

  test-on-main:
    if: github.event_name == 'push'
    name: Test on Main Commit
    runs-on: ubuntu-latest
    needs: test-on-pr
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[test]'
      - name: Run security checks
        run: |
          bandit -r src/content_aggregator
          safety check
      - name: Run type checks
        run: mypy src/content_aggregator 